# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'ko-kr'

# Website info
name: 'Helion의 기술블로그'
description: "엔지니어 생활하며 배우고 경험한 기술을 공유하는 공간 입니다:)"
baseurl: /mediapunta.github.io/
#short_url: 
google_analytics: UA-69281367-1
#disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
#baseurl: /jasper/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
plugins: [jekyll-paginate]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: mediapunta
repo: mediapunta
branch: master
#relative_source: ../jasper/
#destination: ../jasper-pages/
#production_url:  https://mediapunta.github.io/
#production_url:  https://jasper.github.io/jasper/
#source_url:  https://github.com/mediapunta/
#source_url:  https://github.com/jekyller/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
